pipeline{
    agent any
    stages{
        stage("Git")
        {
            steps{
                git 'https://github.com/anilteja8181/studentfinal.git'
            }
        } 
        stage("Maven build")
        {
            steps{
                sh "mvn -f StudentTest/pom.xml clean install compile package"
            }
        }
        stage("Test")
        {
            steps{
                sh "mvn -f StudentTest/pom.xml test"
            }
            post{
                always{
                    junit 'StudentTest/target/surefire-reports/TEST-*.xml'
                }
            }
        }
	    stage('ansible-deploy'){
	      steps{
	          ansiblePlaybook credentialsId: 'ansible-privateKey', disableHostKeyChecking: true, installation: 'ansible', inventory: 'StudentTest/dev.inv', playbook: 'StudentTest/Test.yml'
	      }
	  }
	  
}
}
