pipeline{
    agent any
    stages{
        stage("Git")
        {
            steps{
                git 'https://github.com/anilteja8181/studentfinal.git'
            }
        } 
        stage("Maven build")
        {
            steps{
                sh "mvn -f studentfinal/pom.xml clean install compile package"
            }
        }
        stage("Test")
        {
            steps{
                sh "mvn -f studentfinal/pom.xml test"
            }
            post{
                always{
                    junit 'studentfinal/target/surefire-reports/TEST-*.xml'
                }
            }
        }
	  
}
